# Generated by Django 3.2.5 on 2021-07-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='djangoClasses',
            new_name='djangoClasse',
        ),
    ]
